import { Injectable } from '@angular/core';
import { RandomUtils } from './random.utils';

@Injectable({
  providedIn: 'root'
})
export class StringUtils {

  /**
   *
   * @param strLen the expected string length
   */
  randomDigitsString(strLen: number): string {
    let result = '';
    for (let i = 0; i < strLen; i++) {
      result += this.randomUtils.random(9, 0).toString();
    }
    return result;
  }

  randomName(): string {
    return this.randomUtils.randomValueFrom(this.names);
  }

  randomEmailDomain(): string {
    return this.randomUtils.randomValueFrom(this.emailDomains);
  }

  randomDatasetName(): string {
    return this.randomUtils.randomValueFrom(this.loremNames);
  }

  constructor(
    private randomUtils: RandomUtils,
  ) {}

  private readonly emailDomains = [
    'hotmail.com',
    'outlook.com',
    'msn.com',
    'kenhall.com.au',
    'sa.gov.au',
    'gmail.com',
    'yahoo.com',
  ];

  private readonly loremNames = [
    'Lorem Ipsum',
    'Dolor Sit Amet',
    'Consectetur Adipiscing Elit',
    'Sed Do Eiusmod',
    'Tempor Incididunt',
    'Ut Labore',
    'Et Dolore',
    'Magna Aliqua',
    'Ut Enim Ad Minim',
    'Veniam Quis Nostrud',
    'Exercitation Ullamco',
    'Laboris Nisi Ut',
    'Aliquip Ex',
    'Ea Commodo Consequat',
    'Duis Aute Irure Dolor',
    'In Reprehenderit',
    'In Voluptate',
    'Velit Esse',
    'Cillum Dolore Eu',
    'Fugiat Nulla Pariatur',
    'Excepteur Sint Occaecat',
    'Cupidatat Non Proident',
    'Sunt In Culpa Qui',
    'Officia Deserunt',
    'Mollit Anim Id Est Laborum',
  ];

  private readonly boyNames = [
    'Oliver',
    'William',
    'Jack',
    'Noah',
    'James',
    'Thomas',
    'Lucas',
    'Isaac',
    'Ethan',
    'Alexander',
    'Jacob',
    'Lachlan',
    'Samuel',
    'Harrison',
    'Joshua',
    'Henry',
    'Liam',
    'Cooper',
    'Benjamin',
    'Charlie',
    'Mason',
    'Ryan',
    'Max',
    'Leo',
    'Oscar',
    'Harry',
    'Levi',
    'Daniel',
    'Xavier',
    'Logan',
    'Hunter',
    'Jackson',
    'Archie',
    'Sebastian',
    'Hudson',
    'Jayden',
    'George',
    'Elijah',
    'Joseph',
    'Adam',
    'Riley',
    'Edward',
    'Aidenv Michael',
    'Hugo',
    'Ashton',
    'Flynn',
    'Zachary',
    'Archer',
    'Tyler',
    'Matthew',
    'Nate',
    'Lincoln',
    'Luca',
    'Nicholas',
    'Jaxon',
    'Theodore',
    'Eli',
    'Patrick',
    'Beau',
    'Christian',
    'Harvey',
    'Jake',
    'Finn',
    'Austin',
    'Luke',
    'Dylan',
    'Charles',
    'Connor',
    'Jordan',
    'Gabriel',
    'Kai',
    'Muhammad',
    'Blake',
    'Dominic',
    'Chase',
    'Ali',
    'Braxton',
    'Louis',
    'Nathan',
    'Felix',
    'John',
    'Carter',
    'Angus',
    'Caleb',
    'Marcus',
    'Toby',
    'Anthony',
    'Nathaniel',
    'Hayden',
    'Jasper',
    'Arlo',
    'Andrew',
    'Jonathan',
    'Owen',
    'Harley',
    'Ryder',
    'Hamish',
    'Jesse',
    'Maxwell',
  ];

  private readonly girlNames = [
    'Olivia',
    'Mia',
    'Charlotte',
    'Amelia',
    'Ava',
    'Emily',
    'Chloe',
    'Ruby',
    'Isabella',
    'Sophie',
    'Grace',
    'Ella',
    'Isla',
    'Sophia',
    'Zoe',
    'Sienna',
    'Ivy',
    'Evie',
    'Scarlett',
    'Emma',
    'Lily',
    'Matilda',
    'Hannah',
    'Harper',
    'Zara',
    'Georgia',
    'Lucy',
    'Layla',
    'Abigail',
    'Annabelle',
    'Evelyn',
    'Eva',
    'Isabelle',
    'Jasmine',
    'Willow',
    'Sofia',
    'Audrey',
    'Maddison',
    'Imogen',
    'Jessica',
    'Aria',
    'Mila',
    'Maya',
    'Sarah',
    'Savannah',
    'Alexis',
    'Alice',
    'Stella',
    'Violet',
    'Poppy',
    'Elizabeth',
    'Ellie',
    'Chelsea',
    'Summer',
    'Anna',
    'Claire',
    'Bella',
    'Madison',
    'Victoria',
    'Phoebe',
    'Eloise',
    'Lola',
    'Piper',
    'Indiana',
    'Addison',
    'Holly',
    'Alyssa',
    'Lilly',
    'Eden',
    'Lara',
    'Madeleine',
    'Rose',
    'Ariana',
    'Aaliyah',
    'Paige',
    'Isabel',
    'Lillian',
    'Alexandra',
    'Hayley',
    'Elise',
    'Emilia',
    'Eleanor',
    'Olive',
    'Molly',
    'Eliza',
    'Madeline',
    'Lexi',
    'Penelope',
    'Hazel',
    'Amelie',
    'Harriet',
    'Mackenzie',
    'Jade',
    'Natalie',
    'Elsie',
    'Ayla',
    'Charlie',
    'Indie',
    'Frankie',
    'Samantha',
  ];

  private readonly names = [ ...this.boyNames, ...this.girlNames ];
}
